### ISSUE TITLE
App name is the same as the official Nextcloud News App 

### ISSUE THREAD

**Issue by aproposnix** [bubelov/news#1]
You should really consider renaming the app. It's got the same name as the official Nextcloud News app "News". Very confusing.

**Comment by bubelov** [comment]
@aproposnix renaming to what? That's the Android client for the News web app, it would be confusing to name it otherwise. I'll add a note to the app description and I'll think on other ways to make it more distinctive (maybe changing the logo background color, or something like that).

**Comment by aproposnix** [comment]
Some ideas for names... putting on my marketing cap now (never said i was good at marketing though :) 

* Newsbie
* NewsPod
* RSSpod
* NextNews
* NextPod
* Newscaster 
* Nextcaster 
* Newszilla
* Podzilla 

Ok... I'm running out of ideas. I just think distinguishing projects helps both of them.

**Comment by jancborchardt** [comment]
Hi from Nextcloud @bubelov, nice work! :)

On our Nextcloud Talk instance we have channels for the various apps so contributors can chat with each other – we also e.g. have channels for the News app team (web app as well as mobile apps) and for our Mobile apps too. I can add you there with a guest account if you like?

**Comment by bubelov** [comment]
@jancborchardt hi! That would be nice, thanks! I also run my own instance (igor@cloud.bubelov.com) but I'm not sure how federation works and if it's possible to re-use an existing identity from another server so any option would work for me.

**Comment by bubelov** [comment]
@jancborchardt Hi. Any news on that guest account? It would be nice to be in touch with the News app team =)
