### ISSUE TITLE
Support for built-in Chrome-Tabs

### ISSUE THREAD

**Issue by BluePixel4k** [bubelov/news#105]
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

I had already expressed the suggestion in passing, but a support for built-in Chrome-Tabs would be nice (chromium based browsers support this too).
I don't use Chrome, but it works with Brave too.
The official Nextcloud News App has the feature too.

#### Why do you want this feature?

Because the pages will load faster.

--

Thanks for your work.

**Comment by bubelov** [comment]
I'll look into that later, too much on my plate now. I'm not against this idea, so PRs are welcome, if someone wants to add this feature ASAP

**Comment by BluePixel4k** [comment]
No stress, maybe we can get inspiration from other apps that have implemented the feature.
For example:
https://github.com/nextcloud/news-android
https://github.com/tuskyapp/Tusky

**Comment by emersion** [comment]
Example implementation in Feeder: https://gitlab.com/spacecowboy/Feeder/-/merge_requests/249

**Comment by bubelov** [comment]
> Performance — Here, is a sample provided by Google to see the speed in three different use cases. First, when opening web content in the Chrome browser(Intent). Secondly, opening in chrome custom tabs and lastly, opening in a web view. Chrome Custom Tabs opens 2x times faster.

That sounds good, testing it now

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/38baca3fd2850a74209082271e0b25efcfd6b502

It will appear in the next release, you can also check it out now by installing the preview build

**Comment by BluePixel4k** [comment]
Awesome, it works very well, thank you!
