### ISSUE TITLE
Articles from 1 feed get cut off randomly

### ISSUE THREAD

**Issue by KSPAtlas** [bubelov/news#107]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Use Standalone mode
2. Add feed "https://tuxphones.com/rss
3. Click on an entry

### Actual behavior
 The article gets cut off, sometimes inside a sentence.

### Expected behavior

The full article loads.

### Screenshots/Screen recordings

![IMG_20211125_195119](https://user-images.githubusercontent.com/72895702/143495430-408e78f1-f532-4be3-bbc7-478b213099e1.jpg)

### Device info

 - Android version/Custom ROM version: GrapheneOS Stable security update 1/11/21 (dd/mm/yy)
 - Device model: Google Pixel 3

**Comment by bubelov** [comment]
```
<title>Freedom and phone advice</title>
<description>
A closer look at the smartphone advice from the Free Software Foundation
</description>
```

I'm assuming you're using standalone mode? The app just shows the content of a description tag. Some feeds offer full articles and some feeds prefer to cut them, it depends on feed and not on app. Some backends can try to fetch full content though, you can try that
