### ISSUE TITLE
Hide preview text

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#115]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Make it possible to hide the preview text.

#### Why do you want this feature?

It makes the interface less cluttered and increases content density.

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/09048c2afd7725149ce6e4ed217da165fc37914b
