### ISSUE TITLE
reader: HTML pre texts aren't handled

### ISSUE THREAD

**Issue by frogtile** [bubelov/news#120]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Read a post which has HTML pre text in it
2. Watch that pre texts aren't in monospace and their formating is losr

### Actual behavior

Pre texts are rendered like a paragraph

### Expected behavior

To see pre text in monospace characters, containing their formatting, and having a horizontal scroller if the width of that text is wider than the screen.

### Screenshots/Screen recordings

![Screenshot_20220111-152138](https://user-images.githubusercontent.com/87414805/148915602-ceabcc9c-0480-4d95-b0b2-c3de0e2fe61b.png)

Screenshot of viewing
https://drewdevault.com/2021/12/30/Language-design-considerations.html

**Comment by frogtile** [comment]
@bubelov can you please take a took at this issue

**Comment by frogtile** [comment]
@bubelov can you please take a took at this issue

**Comment by bubelov** [comment]
Moved to https://github.com/bubelov/news/issues/137
