### ISSUE TITLE
Can't add feed not having absolute URI for them

### ISSUE THREAD

**Issue by frogtile** [bubelov/news#122]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Try Adding the feed from https://scattered-thoughts.net using https://scattered-thoughts.net 

### Actual behavior

It failed with an error message saying, " URI isn't absolute"

### Expected behavior

To add the feed successfully, by evaluating the relative URI to an absolute one from

```
<link title="Scattered Thoughts" href=/atom.xml rel=alternate type=application/atom+xml>
```

**Comment by frogtile** [comment]
From this I also learned that HTML element's attribute value doesn't always need to be double quoted

https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

**Comment by bubelov** [comment]
@frogtile you're using standalone mode, right?

**Comment by bubelov** [comment]
Fixed in https://github.com/bubelov/news/commit/117e8bf6936dbfb2ccc2b8293bf75f887d053028

**Comment by bubelov** [comment]
@frogtile FYI: you can also omit http(s)://, just typing a domain name should work

**Comment by frogtile** [comment]
> @frogtile you're using standalone mode, right?

Yes
