### ISSUE TITLE
UI: open in browser button is hiding content

### ISSUE THREAD

**Issue by frogtile** [bubelov/news#123]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open an article.
2. Scroll to the end.

### Actual behavior

Texts behind the button is not viewable

### Expected behavior

To be able to read the full article

### Screenshots/Screen recordings

![Screenshot_20220113-021547](https://user-images.githubusercontent.com/87414805/149215666-e42b59c4-a338-4400-b5a3-b36f5dc415d2.png)

**Comment by bubelov** [comment]
Fixed in https://github.com/bubelov/news/commit/83e84c4635b43c0ed391109f84f40adbab3198bd
