### ISSUE TITLE
No 'download's button when using search in podcast feed

### ISSUE THREAD

**Issue by adrienneteicher** [bubelov/news#129]
### Checklist

- [x] I am using the latest version 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

The "download" button does not appear in the search results

### Expected behavior

The “download" button should appear for each result as when browsing a podcast without using search

### Screenshots/Screen recordings

![Screenshot_20220208-010658](https://user-images.githubusercontent.com/28346272/152893042-ff6a19aa-c11f-4b62-94c4-f8694a229382.png)
![Screenshot_20220208-010650](https://user-images.githubusercontent.com/28346272/152893059-9f3164e3-c8b3-420a-8088-8393d55a69dc.png)

### Device info

 - Android version/Custom ROM version: Calyx, Android 12
 - Device model: Pixel 3 XL

**Comment by bubelov** [comment]
Fixed in https://github.com/bubelov/news/commit/20295ff9969822b592f5285ce2a642cb54ebca19

**Comment by adrienneteicher** [comment]
Cheers
