### ISSUE TITLE
Remove settings from bottom navigation

### ISSUE THREAD

**Issue by bubelov** [bubelov/news#14]
I've been reading Material spec and I found the following recommendation:

> Bottom navigation shouldn’t be used for:
> 
> - Single tasks, such as viewing a single email
> - User preferences or settings

https://material.io/components/bottom-navigation#usage

**Comment by bubelov** [comment]
@Antoine-Derouin do you have any advice on that?

**Comment by Antoine-Derouin** [comment]
In many apps, the settings button is in the burger menu.
But creating a burger just for this button is a really bad idea...

Can you offer several buttons?

Unread news
All News
Bookmark
Feeds
Settings

And put the burger in the header?

Or like TTRSS :
The burger opens a panel with the settings button, then a list of feed folders, and an "unread only" toggle.

**Comment by bubelov** [comment]
@Antoine-Derouin thanks for the advice!

> And put the burger in the header?

Just to clarify: do you mean the thing on the left or the thing on the right?

![Screenshot from 2021-01-14 13-08-34](https://user-images.githubusercontent.com/1189245/104551769-11cb7280-566a-11eb-99a5-6716b87ef9e7.png)

**Comment by Antoine-Derouin** [comment]
I'm talking about the left button.

I see the burger menu, with three lines like opening a general menu panel. (identical throughout the app)

.

The three little dot icon would make me think more about options specific to the current display. Like a context menu.

**Comment by seldon1000** [comment]
@bubelov I would like to share some thoughts. I don't think adding a hamburger menu is a great idea. Google is gradually removing it from their apps as Material Design guidelines are evolving to better support long aspect ratios and side navigation gestures. Probably, what's best in this case is a Bottom Drawer, like a classic Modal Drawer but anchored at the bottom (it follows your app's style). 

More infos: https://material.io/components/navigation-drawer#bottom-drawer

The link even mentions the possibility to add an account switcher (could be good for Nextcloud). However, the activation of the Bottom Drawer is tricky: a button on the top app bar would be inconsistent and inconvenient, while a gesture would interfere with system's navigation gestures.

**Comment by bubelov** [comment]
Closing because new navigation structure doesn't have this issue
