### ISSUE TITLE
adding a http feed fails

### ISSUE THREAD

**Issue by ildar** [bubelov/news#144]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Tap `+` to add a feed
2. insert `http://lifehacker.ru/feed/`
(not httpS)

### Actual behavior
error: host `http` not found

### Device info

 - Android version/Custom ROM version: AOSP 12 by Phh
 - Device model: Doogee S59 pro

**Comment by bubelov** [comment]
It works fine in the preview build: https://github.com/bubelov/news/releases/tag/preview

Please note that those builds are made automatically from the most recent commit and they can be pretty unstable. You can grab a preview build if you really need that feed and can't wait for the next official release (no ETA on that yet)

![device-2022-05-27-134512](https://user-images.githubusercontent.com/1189245/170646342-978dcb4c-6a53-4e08-8633-8b422712a06b.png)
![device-2022-05-27-134542](https://user-images.githubusercontent.com/1189245/170646357-e38845e6-650e-485c-9734-2220e3881b88.png)
