### ISSUE TITLE
Some rss links do not work

### ISSUE THREAD

**Issue by Darkempire78** [bubelov/news#149]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Add this rss feed : https://partner-feeds.20min.ch/rss/20minutes
2. Refresh
3. See that the feed does not work

### Actual behavior
News is not able to "decrypt" the rss feed. It finds no article from the feed

### Expected behavior
Find the articles

### Logs
I cannot find the logs in the settings 🤔

### Device info

 - Android version: Android 12
 - Device model: Pixel 6

**Comment by bubelov** [comment]
> Failure(java.lang.Exception: Enclosure length is missing)

https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fpartner-feeds.20min.ch%2Frss%2F20minutes

This is an invalid feed, you can report this issue to feed maintainers
