### ISSUE TITLE
HTML entities rendering as plain text in titles

### ISSUE THREAD

**Issue by aaron-watts** [bubelov/news#151]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

HTML entities such as '$' and '£' do not render in title

### Actual behavior

HTML entities render in plain text: <pre>£#163;</pre> instead of £

### Expected behavior

Can title html entities be rendered as what they correspond to?

### Screenshots/Screen recordings

![Screenshot_20220728-072750_News.jpg](https://user-images.githubusercontent.com/65028208/181438842-f97fd363-26a4-4229-9a47-c924f2723f84.jpg)

### Device info

 - Android version/Custom ROM version: Android v12
 - Device model: Samsung A52

**Comment by bubelov** [comment]
@aaron-watts can you provide feed URL? First, we need to make sure this feed is valid

**Comment by aaron-watts** [comment]
https://feeds.skynews.com/feeds/rss/world.xml

**Comment by bubelov** [comment]
Fixed in https://github.com/bubelov/news/commit/1ae5972434aae88504ac53f2ed59affe120552d4

@aaron-watts preview releases with the latest changes and bugfixes are always available here: https://github.com/bubelov/news/releases/tag/preview
