### ISSUE TITLE
[FR] Open article in browser

### ISSUE THREAD

**Issue by dontobi** [bubelov/news#158]
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
It would be helpful to add the option "open article in browser" in the 3-dot menu of the article view.

#### Why do you want this feature?
Some RSS feeds do not deliver the entire article.
Currently you have to copy the link of the article via the share function and paste it into browser.

**Comment by bubelov** [comment]
@dontobi do you see a floating action button in the bottom-right corner of that screen? Let me know if its missing. Also, you can go to feed settings screen and set those shortened feeds to open in browser by default.

**Comment by dontobi** [comment]
On my Pixel 6 with Android 13, my floating button is displayed (see screenshot).

![Screenshot_20220906-091428](https://user-images.githubusercontent.com/19261667/188571171-af2ae1a8-c7d8-4ba2-8b3f-16cbbfc94890.png)


The option with the integrated browser doesn't seem to work either, because the view of the articles stays the same, no matter if I turn the feature on or off.

**Comment by bubelov** [comment]
@dontobi every feed has its own settings, you can access it from the feeds screen or from any feed entry screen

**Comment by dontobi** [comment]
Thank you for pointing it out. These feed related settings I did not know until now.
However, I am now wondering what option "use the internal browser" in the settings does. I could not see any difference so far, no matter what I selected in this option.

**Comment by bubelov** [comment]
@dontobi internal browser is generally faster, but if you don't see any difference, there is no need to turn it on. Some users asked for it and they reported better performance (measured as page loading time).

**Comment by dontobi** [comment]
Okay. Thanks for the explanation.
