### ISSUE TITLE
Nextcloud Sync does not work

### ISSUE THREAD

**Issue by dontobi** [bubelov/news#159]
### Checklist
- [x] I am using the latest version
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Install latest Debug Version (09.09.2022)
2. Setup the App with Nextcloud Sync

### Actual behavior
With the current debug version the sync with my Nextcloud does not work. With the debug version from 05.09.2022 the error does not occur.

### Expected behavior
The Nextcloud sync should work.

### Screenshots
![Screenshot_20220909-205918](https://user-images.githubusercontent.com/19261667/189424494-f7f204c5-4cf0-4e30-a71a-aaa9f63fcc9b.png)
![Screenshot_20220909-205931](https://user-images.githubusercontent.com/19261667/189424502-41bb6d63-1ff9-4993-b608-58406c8da01d.png)

### Logs
None

### Device info
 - Android version: 13
 - Device model: Google Pixel 6

**Comment by bubelov** [comment]
Still not working?

**Comment by dontobi** [comment]
It's working. Closed
