### ISSUE TITLE
News no longer recovering any articles

### ISSUE THREAD

**Issue by Darkempire78** [bubelov/news#161]
### Checklist

- [x] I am using the latest version (PREVIEW BUILD)
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

News no longer get articles (I tried with more than 15 feeds wich worked before)

### Expected behavior

Receive latest articles

### Logs

I'm using the autonomous version

### Device info

 - Android version/Custom ROM version: Android 13
 - Device model: Pixel 6

**Comment by bubelov** [comment]
Should be fixed in https://github.com/bubelov/news/commit/48788f640cace86cba9184e96071ea287fbd3248
