### ISSUE TITLE
Filter out certain entries based on customizable set of rules

### ISSUE THREAD

**Issue by zynexiz** [bubelov/news#17]
Just thought of a cool feature I actually never seen in any feed app as I know of. Some feeds might include topics I'm not very interested of (like sports), and it would be a nice feature to add some kind of "blacklist" filter that excludes topics containing certain keywords. It could then automatically mark then as read and don't add then to the feed.

There could also be a similar whitelist filter that marks the topic as important, and add a "Important" tab for it?

The configuration could be done globally or individually for each feed.

Not sure how big of a undertaking this would be, but it would be really cool feature I think :)

**Comment by bubelov** [comment]
@zynexiz I like this idea, I've been thinking about it too. I have a bunch of "verbose" feeds such as Hacker News (which also embed annoying ads) so it would be nice to be able to filter out some nasty entries.

Let's say we can start simple and add a rule like "if this entry contains string X, ignore it". It's a bit unclear whether we should have a single global blacklist or a set of unique "bad words" per feed. I'm leaning towards "per feed" solution. 

I didn't think it trough yet so any ideas are welcome. I have nothing against such a feature in general and I can implement it.

**Comment by zynexiz** [comment]
I think a per feed list would be best, to avoid filtering out topics from other feeds that might match the word. I would have helped, but never coded Java and nothing on android so far, have it on my big todo list 😃

**Comment by bubelov** [comment]
@zynexiz I didn't touch Java for about 4 years, it's all Kotlin now. Good riddance, Android only supports ancient versions of Java so Kotlin had really saved the day.

**Comment by zynexiz** [comment]
Ah, I will look into that one day. Taking courses at my university in CCNA, CCNP, cybersecurity and networking, so not much time over right now. Wish the day would be longer sometime :)

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/79929215c55ad0b52d541df2651bb1bc9f987d25
