### ISSUE TITLE
Floating button to open article disappeared

### ISSUE THREAD

**Issue by GuillaumeLeGoc** [bubelov/news#170]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I am using the latest version 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Open an entry from the feed.

### Actual behavior

The floating button that was in the bottom right corner is not here anymore, I can't open the article in web browser. 

### Expected behavior

Restore the floating button that was here in 0.3.4 and disappeared in 0.4.
Only workaround is to set "Open entries in browser" for each feed, but I liked being able to read the header before opening (or not) the article.

Cheers

**Comment by GuillaumeLeGoc** [comment]
Update : actually, the floating button appears if you scroll the entry. But for short entries, there's not enough text to scroll and the button does not appear.

**Comment by mormegil-cz** [comment]
Are you using Nextcloud? Because AFAICT there is a severe bug in Nextcloud synchronization which prevents showing the button. However, it is partially reversed by _another_ bug which shows the button on scrolling. :-)

**Comment by GuillaumeLeGoc** [comment]
Yea I'm using Nextcloud. And in fact the button appears if I'm able to scroll (which is almost never the  case), but the button does not open anything.

**Comment by mormegil-cz** [comment]
Oh, right. As I said, _partially_ reversed. :-) I forgot that even then, the link action would not be set. I just pushed a PR which should hopefully fix this (after a reimport, I’m afraid).

**Comment by bubelov** [comment]
Everyone affected: you can try the latest preview build and see if it works: https://github.com/bubelov/news/releases/tag/preview

It includes a few promising patches sent by @mormegil-cz, re-installing the app might be necessary

**Comment by GuillaumeLeGoc** [comment]
Yay, this release fixes the problem. Button shows up and works, nice work :)
