### ISSUE TITLE
OPML Import failure: Collection contains no element matching the predicate

### ISSUE THREAD

**Issue by glacambre** [bubelov/news#178]
### Checklist

- [x] I am using the latest version
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo (although https://github.com/bubelov/news/issues/153 might be related).
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Load the following OPML file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.1">
  <head>
    <title>
      Feeder
    </title>
  </head>
  <body>
    <outline title="Writing - rachelbythebay" text="Writing - rachelbythebay" type="rss" xmlUrl="https://rachelbythebay.com/w/atom.xml"/>
  </body>
</opml>
```

### Actual behavior
News fails with the following error message: `Failed to import feed $URL Reason: Collection contains no element matching the predicate.`.

### Expected behavior
The feed is correctly loaded. As far as I can tell, this feed is 100% correct. The only uncommon thing that I'm seeing is that some entries are missing a "summary" tag, but this is allowed by the spec AFAIU.

### Device info

 - Android version/Custom ROM version: Stock android 13.
 - Device model: Pixel 4A.

P.S.: Sorry about opening all these issues, this should be the last one :). It's really great that News is vocal about problems in the feeds being imported - most of the apps I tried fail silently and this resulted in a ton of invalid entries/expired domains staying around in my decade-old OPML file. News enabled me to notice some problems and clean them up, so thanks again for building and maintaining it!

**Comment by bubelov** [comment]
This feed appears to be invalid: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frachelbythebay.com%2Fw%2Fatom.xml
