### ISSUE TITLE
Item description/content disappeared from 0.4.0

### ISSUE THREAD

**Issue by BlackLight** [bubelov/news#179]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Upgrade the app to 0.4.0
2. Open an item in the list
3. Even if the item had a description/content field in the feed, that is not shown in the app. The only way to see the item is to open it in browser.

4. Downgrade to 0.3.4
5. Everything works as expected

### Actual behavior

No content

### Expected behavior

Content should be there

### Device info

 - Android version/Custom ROM version: tried both on stock Android 11 and Android 12 (LineageOS ROM) 
 - Device model: tried on OnePlus6, Nexus 7 and Lenovo Tab

**Comment by BadCo-NZ** [comment]
Same issue here too

**Comment by gzqx** [comment]
Same. Using minflux

**Comment by vivithecanine** [comment]
Same here using miniflux

**Comment by scottsweb** [comment]
This is still the case with 0.4.1 from F-droid using a Miniflux server - all articles are empty:

![Screenshot_20221220-220109](https://user-images.githubusercontent.com/411945/208765951-80d3f305-7345-4d64-bdf6-934e2a7dc96a.png)

**Comment by BadCo-NZ** [comment]
I have been using [Miniflutt](https://github.com/DocMarty84/miniflutt) and actually have been liking it. I do miss the picture previews though.

**Comment by Visne** [comment]
Should be fixed when #192 is merged 😄

**Comment by bubelov** [comment]
Merged. The people affected can use a preview build to verify that it works: https://github.com/bubelov/news/releases/tag/preview

**Comment by scottsweb** [comment]
Tested the preview build and I can see the content now. I do have a weird rendering issue with posts containing images though. They tend to reload over and over again which causes the article to jump around. It's almost as though someone is hitting refresh on a web browser every fraction of a second.

**Comment by Visne** [comment]
Does that happen for every feed? Because that's not happening for me.

**Comment by scottsweb** [comment]
Every feed with an image that I tested unfortunately (which was about 4 different feeds).
