### ISSUE TITLE
Open news directly in the Browser (optionally)

### ISSUE THREAD

**Issue by BluePixel4k** [bubelov/news#18]
Can you add an option in the settings, to open the news directly in the Browser? 
Not all my news providers have a full-text feed.

And support for built-in Chrome-Tabs would be nice (chromium based browsers support this too).

**Comment by bubelov** [comment]
@BluePixel4k 

Regarding browser: yes, sounds good

Regarding Chrome stuff: I have to look into it first. If it doesn't require any Google dependencies, I'll add it in future releases

**Comment by BluePixel4k** [comment]
Thank you!
Regarding Chrome stuff, i think yes, because the official Nextcloud News App has the feature too.

**Comment by BluePixel4k** [comment]
If it's possible, another option would also be great, where you can set for each feed individually whether it should always be opened in the browser or internally (for full text feeds).

**Comment by bubelov** [comment]
@BluePixel4k yes, I think adding "feed settings" screen is the best option

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/22359ef3f6dfe21f0fec2e75958a429aa9b430de
