### ISSUE TITLE
After update to 0.4.0 credential configuration is lost

### ISSUE THREAD

**Issue by miicha** [bubelov/news#180]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Have 0.3.4 installed and configured (in my case miniflux) 
2. Update to 0.4.0

### Actual behavior

- First configuration screen shows up
- adding (miniflux)  credentials leads to #179 

### Expected behavior

- configuration still valid
- feeds/entries are shown

### Device info

 - Android version/Custom ROM version: 11

**Comment by bubelov** [comment]
https://github.com/bubelov/news/issues/172#issuecomment-1281187981
