### ISSUE TITLE
Support for 2-Factor-Authentication (2FA)

### ISSUE THREAD

**Issue by Menjuel** [bubelov/news#185]
I am using nextcloud with 2fa enabled and I see no way how I can log into the app. Like other apps I tried putting my 2fa code behind my passsword seperated by a colon but that doesnt work.

I really like the app otherwise, but that a dealbraker for me :(

**Comment by LeafyOtter** [comment]
In your nextcloud settings you can add an application. It will give you the credentials you need.

Settings > Security > Devices & Sessions

**Comment by bubelov** [comment]
You can always create app tokens which doesn't require 2fa, as far as I know.

**Comment by Menjuel** [comment]
Thank you guys! It worked. Closing this. I suggest to point this out in the docu or in the app itself.
