### ISSUE TITLE
Variable background sync with notification

### ISSUE THREAD

**Issue by BluePixel4k** [bubelov/news#19]
Can you add a background auto sync feature?
A variable sync interval would be great.
For example: every hour, every three hours or every 12 hours.

And if there are new news, then a notification would be great.

**Comment by bubelov** [comment]
@BluePixel4k yes, it will be added in the future. I'd like the app to update feeds and download podcasts automatically. Not a big fan of notifications though, but they can be disabled by default with the ability to opt-in in settings.

**Comment by BluePixel4k** [comment]
That sounds great, thanks!

**Comment by cryptomilk** [comment]
I'm also interested in hourly sync and notifications :-)

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/69c5291bb59f9c62e56e7c48fb95b64a12ffcb26
