### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Antoine-Derouin** [bubelov/news#2]
Hello, thank you for the app.
I tested it quickly, although minimalist it does the job and above all it has a very nice material 2 style!

I just have a few comments on the points that disturbed me:

- Not being able to easily switch "Show opened news" from the "News" tab.
- Not being able to see the news of a single feed (including those already read)
- The swipe to right does not explicitly show that it adds to the bookmarks (I just thought I'd mark it as read)
- Not being able to reverse swipe to right & left actions

Congratulations on the work, I've been looking for a RSS material 2 client for a long time!

**Comment by bubelov** [comment]
@Antoine-Derouin thanks for your feedback! Good points, I'll include all of these features in the next releases. The next one will be available in January (I'm on vacation now and the project is on hold till the new year).

**Comment by bubelov** [comment]
Broken into separate issues #8 #9 #10 #11
