### ISSUE TITLE
[BUG] Unable to remove bookmark

### ISSUE THREAD

**Issue by zynexiz** [bubelov/news#20]
I accidentally added a article to the bookmarks by swiping the article to the left (right?). And when i went to the bookmarks tab and tried to swipe it again, it just said added to bookmark again. When swiping in the bookmarks section, the result should be to remove it.

Might also suggest adding some kind of hint what will happen when starting to swipe, like most e-mail applications have. While starting to move the item to left or right, most apps have a symbol appearing to hint what is about to happen.

**Comment by zynexiz** [comment]
Found a image illustrating what I mean :)

![Swipe](http://tapsmart.wpengine.netdna-cdn.com/wp-content/uploads/2015/06/swipe-to-delete-911x1024.png)

**Comment by bubelov** [comment]
@zynexiz it's a known issue. Partly fixed in #10 which is already live but, sadly, still not picked up by F-Droid. As for swipes in general, they weren't supposed to be allowed on favorites screen but then I decided to merge the controllers and forgot to disable swipes. It's already fixed in master and will be available with the next release.

**Comment by zynexiz** [comment]
@bubelov Oh, how could I miss that one :)

Kinda resolved, so I close it.

**Comment by Tiger3030** [comment]
> Might also suggest adding some kind of hint what will happen when starting to swipe, like most e-mail applications have. While starting to move the item to left or right, most apps have a symbol appearing to hint what is about to happen.
> 
> Found a image illustrating what I mean :)
> 
> ![Swipe](https://camo.githubusercontent.com/1fa79e3783ec9853ac3d38cdc56f79e544002dc294122b10f49323cb0da98449/687474703a2f2f746170736d6172742e7770656e67696e652e6e6574646e612d63646e2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031352f30362f73776970652d746f2d64656c6574652d39313178313032342e706e67)

@bubelov I also think this would improve the user experience a lot. Do you plan to implement this?

Also, in my opinion the snackbar should be shown a little longer, because at the moment it is gone so fast that it is almost impossible to press the 'undo' button.

**Comment by bubelov** [comment]
@Tiger3030 this app follows Material Design and uses only official patterns and components. I'm not aware of such a pattern and I don't remember seeing it in Android apps. If you can find a good recommendation or a component in Material spec, I will most likely add it.

Other option would be adding tutorial overlays. Not a big fan, but it's better than nothing.

**Comment by Tiger3030** [comment]
It is used for example in the Gmail Android app (which follows Material Design as far as I know).

In the Material Design guidelines you can find it here: https://material.io/components/lists#behavior (you have to scroll down to 'Gestures')

**Comment by bubelov** [comment]
@Tiger3030 there are no code examples here. Quick look trough their libs didn't reveal anything this app could use. Gmail animation also looks different and less nice =)

This guy did something similar with little new code, I'll try his approach to see if it works with card widgets.

https://medium.com/@kitek/recyclerview-swipe-to-delete-easier-than-you-thought-cff67ff5e5f6
