### ISSUE TITLE
Standalone mode bug

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#21]
Many feeds cause an error in News in standalone mode.

Examples:
1. http://www.theverge.com/rss/full.xml
2. http://www.nos.nl/nos/rss/nieuws.xml
3. https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw

All lead to the same error: CLEARTEXT communication to <domain> not permitted by network security policy.

Here are the logs:

![1](https://user-images.githubusercontent.com/50382414/107439926-213bbf80-6b33-11eb-8aa0-0559ce03ade9.png)
![2](https://user-images.githubusercontent.com/50382414/107439945-26007380-6b33-11eb-914d-0cbd324d1cae.png)
![3](https://user-images.githubusercontent.com/50382414/107439960-2993fa80-6b33-11eb-8b20-9524bb6bb964.png)
![4](https://user-images.githubusercontent.com/50382414/107439967-2d278180-6b33-11eb-981b-89fa681565e7.png)

I have only found one feed that does not lead to this exceptions. The URL is https://www.reddit.com/r/fossdroid/.rss

**Comment by bubelov** [comment]
@Donkey-Doug thanks for the detailed report. First two feeds are insecure so the app won't allow them. I added a special error message and a suggestion to use HTTPS to get those feeds added.

![Screenshot_1612969037](https://user-images.githubusercontent.com/1189245/107529189-3412ca80-6bed-11eb-9c0d-ffd44943f1bf.png)

**Comment by bubelov** [comment]
@Donkey-Doug apart from that particular issue, standalone mode is untested and standalone parser is far from being complete. I wouldn't recommend do use it for now, unless you want to help with finding broken feeds. I found a few parsing issues with the feeds you sent and I'll add them to the test suite.

**Comment by Donkey-Doug** [comment]
@bubelov Could you maybe warn the user that the http link is insecure and still have the option to "continue anyway"?

**Comment by bubelov** [comment]
@Donkey-Doug yea, I was thinking about an option in settings, the problem with alerts is that there are too much of them and people tend to skip text and press OK no matter what is offered. If someone intentionally goes to settings and enables it, it probably means that they understand the risks. I'll split it into a separate issue
