### ISSUE TITLE
Copy error text

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#22]
Make it possible to copy the text from the exceptions. Preferable add a button "copy text" next to the OK button.

**Comment by bubelov** [comment]
@Donkey-Doug makes sense. I'll add "share" button to each exception. That way, users will be able to share the stack trace to clipboard as well as to any other destination (maybe email, instant messaging apps and so on).

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/01cf6e6db32955bc22ecb57518e59112361ffd5b
