### ISSUE TITLE
Unread count on feeds

### ISSUE THREAD

**Issue by zynexiz** [bubelov/news#23]
Noticed there is nowhere to see how may unread articles there are on one feed. My suggestion would be to add a small badge to the feed tab on each article to indicate the number of unread articles for that feed. Attached a screen shot how it might look :)

Also, I would love to help to translate the app to Swedish :)

![Screenshot](http://www.image-share.com/upload/4129/126.png)

**Comment by bubelov** [comment]
@zynexiz yea, it's a planned feature. Let's keep this issue open so I won't forget to add it.

PS. Moved the translation questions to #24

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/77962aaf0f83026ea1f03c6afc128554edbc8827
