### ISSUE TITLE
Add Swedish translation

### ISSUE THREAD

**Issue by bubelov** [bubelov/news#24]
@zynexiz would your translation be understandable in all of the listed regions or only in Sweden?

![Screenshot from 2021-02-10 22-38-36](https://user-images.githubusercontent.com/1189245/107532968-04fe5800-6bf1-11eb-891d-ecf7621a6128.png)

**Comment by zynexiz** [comment]
In Åland they speak Swedish as far as I know, many from Finland know Swedish to but Finnish language is completely different from Swedish otherwise.

**Comment by bubelov** [comment]
@zynexiz great, I guess it could be a universal translation then. I've created a special "strings" file which you can translate (partly or fully):

https://github.com/bubelov/news/blob/master/app/src/main/res/values-sv/strings.xml

Feel free to change the English values to the Swedish ones, this file will only be used by devices with Swedish locale.

**Comment by zynexiz** [comment]
Sweet, I will take a look at it later today if there some time over from my studies :)

**Comment by zynexiz** [comment]
Wasn't to many strings to translate, so it went pretty quick :)

[code]
<resources>
    <string name="app_name">Nyheter</string>
    <string name="login_with_nextcloud">Logga in med Nextcloud</string>
    <string name="post_image">Artikelbild</string>
    <string name="settings">Inställningar</string>
    <string name="news">Nyheter</string>
    <string name="show_opened_news">Visa lästa nyheter</string>
    <string name="hide_opened_news">Göm lästa nyheter</string>
    <string name="bookmark">Bokmärken</string>
    <string name="remove_bookmark">Ta bort bokmärke</string>
    <string name="logo">Logo</string>
    <string name="log_out">Logga ut</string>
    <string name="log_out_warning">Är du säker på att du vill logga ut?</string>
    <string name="cancel">Avbryt</string>
    <string name="login">Logga in</string>
    <string name="direct_login_failed">Kan inte ansluta till server. Kontrollera uppgifterna.</string>
    <string name="server_url_hint">https://mycloud.com</string>
    <string name="username">Användarnamn</string>
    <string name="password">Lösenord</string>
    <string name="news_list_is_empty">Nyhetslistan är tom</string>
    <string name="you_have_no_bookmarks">Det finns inga bokmärken</string>
    <string name="field_is_empty">Fältet är tomt</string>
    <string name="error">Fel</string>
    <string name="download">Ladda ner</string>
    <string name="downloading">Laddar ner</string>
    <string name="listen">Lyssna</string>
    <string name="crop_feed_images">Beskär artikelbilden</string>
    <string name="exceptions_logged_d">Felmeddelande loggad: %1$d</string>
    <string name="exceptions">Felmeddelanden</string>
    <string name="you_have_no_logged_exceptions">Det finns inga loggade fel</string>
    <string name="feeds_list_is_empty">Flödet är tomt</string>
    <string name="feeds">Flöden</string>
    <string name="bookmarks">Bokmärken</string>
    <string name="delete_all">Ta bort alla</string>
    <string name="open_xml_link">Öppna flöde</string>
    <string name="open_html_link">Öppna webbplats</string>
    <string name="actions">Åtgärder</string>
    <string name="delete">Ta bort</string>
    <string name="unknown_feed">Okänt flöde</string>
    <string name="add_feed_url_hint">Klistra in adressen till flödet här</string>
    <string name="add_feed">Lägg till Flöde</string>
    <string name="add">Lägg till</string>
    <string name="show_feed_images">Visa nyhetsbilder</string>
    <string name="view_exceptions">Visa fel</string>
    <string name="rename">Byt namn</string>
    <string name="feed_title">Flödestitel</string>
    <string name="cannot_find_entry_with_id_s">Kan inte hitta inlägg med id %1$s</string>
    <string name="cannot_show_content">Kan inte visa innehåll</string>
    <string name="share">Dela</string>
    <string name="nextcloud_login">Nextcloud inloggning</string>
    <string name="delete_all_data">Ta bort all data</string>
    <string name="delete_all_data_warning">Detta kommer nollställa appen och ta bort all data.</string>
    <string name="standalone_mode">Självständigt lägt (beta)</string>
    <string name="open_in_browser">Öppna i webbläsare</string>
    <string name="do_you_want_to_connect_to_nextcloud">Vill du ansluta till din NextCloud server manuellt?</string>
    <string name="yes">Ja</string>
    <string name="no">Nej</string>
    <string name="show_newest_first">Visa nyaste först</string>
    <string name="show_oldest_first">Visa äldsta först</string>
    <string name="marked_as_read">Markera läst</string>
    <string name="bookmarked">Tillagt till bokmärken</string>
    <string name="search">Sök</string>
    <string name="clear_search_input">Rensa sökningen</string>
    <string name="no_results">Inga resultat</string>
    <string name="you_have_no_apps_which_can_play_this_podcast">Du har inga appar som kan spela upp denna podcast.</string>
    <string name="import_feeds_from_opml_file">Importera flöde från OPML-fil</string>
    <string name="export_feeds_to_opml_file">Exportera flöde till OPML-fil</string>
    <string name="undo">Ångra</string>
</resources>
[/code]

**Comment by bubelov** [comment]
@zynexiz just merged your file, thanks! 

FYI: You could also edit this file via GitHub web interface. It can create merge requests automatically so there is no need to download, edit and upload files. Might be easier and faster this way if you want to correct something or translate a new string.
