### ISSUE TITLE
Remove top bar

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#25]
The top bar currently does nothing. It only displays the text "news". I suggest entirely removing the bar. Having both a top and bottom bar is too cluttered in my opinion.

**Comment by zynexiz** [comment]
There are also some options there. Almost every android app has it, and contains  burger menu, options menu and other stuff.

**Comment by Donkey-Doug** [comment]
I use the app in standalone mode. For me it is only bar without any buttons
