### ISSUE TITLE
True black dark mode

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#29]
Please make it possible to use true black dark mode.

**Comment by bubelov** [comment]
@Donkey-Doug Android doesn't seem to support more than two default modes:

![Screenshot from 2021-04-18 01-45-50](https://user-images.githubusercontent.com/1189245/115123574-edc05a00-9fe7-11eb-86fc-40d21de21f28.png)

It's possible to hard-code additional modes and implement app-specific theme management but it would complicate the code quite a bit and it's not really a good practice. Material Design spec defines colors and themes and this app aims to be conformant with it. It doesn't even have a theme picker, it just follows the system settings.
