### ISSUE TITLE
Add option to mark items as read after scrolling past them

### ISSUE THREAD

**Issue by anoadragon453** [bubelov/news#3]
I have quite a lot of items in my news feed. Often I scroll past the ones I don't care to read. It'd be nice if there was an option that marked these items as read once I'd scroll past them, so I don't  see them the next time I open this app.

https://f-droid.org/packages/de.luhmer.owncloudnewsreader has a similar feature which I really appreciate.

Thanks for the app regardless! Love the design and large image previews!

**Comment by zynexiz** [comment]
Just found this app, and it looks loot nicer than the official app. But I have the same issue, have to read the item to get it marked as read. Might also suggest adding "Mark all read.." as an option to the feed and/or individual feeds to? Maybe even open a dialog to select articles older than like X day/week/month etc as read? :)

**Comment by bubelov** [comment]
@zynexiz I've never thought of this use case, you must have a lot of feeds =) 

So, you have the same issue as @anoadragon453 and auto-marking all of the visible items as "read" would solve it?

**Comment by zynexiz** [comment]
@bubelov I have some, mostly some news stuff. But they tend to post lots of articles per day, can be up to 100 per day, but I mostly read like 10% of it. So much to do and so little time :) I still have NextCloud news installed so I can mark stuff as read.

**Comment by anoadragon453** [comment]
I have a feed which shoots out turns out articles per day. But I like to skim the title of each one and read the interesting ones, even if they're 6mo old or whatnot. I don't think I'll ever get to the end to where I'd want to hit "Mark all read".

Instead, marking individual items as read as I scroll through them would be my preferred workflow.

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/0aa7a9a97826b9623d11278a9489b5baf27e0a05

**Comment by anoadragon453** [comment]
Wonderful thank you!
