### ISSUE TITLE
Remove scrollbar

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#30]
When scrolling through my feed, there is a scrollbar on the right side. I do not think this has a purpose and I would like to hide it.

**Comment by bubelov** [comment]
@Donkey-Doug it has at least three purposes:

- Show user that the content is scrollable
- Indicate user position in a list 
- Give user a hint about the size of a list

I have nothing against having it as an "opt in" feature, but every feature needs regular maintenance and there are currently no people who need is and can commit to implementing and maintaining it.
