### ISSUE TITLE
Consistent layout

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#35]
Currently there is a tab "feeds" in which a single feed can be added by URL. To add feeds using an OPML file, the user has to go to settings. I suggest bringing these functions together in the same screen/menu.

For example, see screenshot below:
![Screenshot_20210222-234705_NiceFeed_1](https://user-images.githubusercontent.com/50382414/108780451-bf367d80-7568-11eb-8084-a8b070e01251.png)

**Comment by bubelov** [comment]
@Donkey-Doug good idea, noted. I'm planning to remove the settings tab (see #14) because it's against Material guidelines. It will probably be available via global side menu, but feed actions aren't really global so I'll move them to the feeds tab instead.

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/a131ee703abc0b63e1aca17d75fd710f12f10ada
