### ISSUE TITLE
Inconsistency with show/hide read items

### ISSUE THREAD

**Issue by zynexiz** [bubelov/news#37]
In the main view, when selecting "Show/hide read news" the read items are hidden or showed as expected. But when going to the individual feeds, the function is reversed, hidden items is shown. In the screenshot, the two first ones are from the main feed. There it works as expected. The last one is from an individual feed, and the function is reversed there.

![news_sceenshot](https://user-images.githubusercontent.com/22789493/109383031-23986a80-78e4-11eb-81c3-29db7b676c3d.jpg)

**Comment by bubelov** [comment]
Fixed in https://github.com/bubelov/news/commit/94afdb39a41c94eabdc11dd92b36bcf41cb5b6b9
