### ISSUE TITLE
Add search in bookmarks

### ISSUE THREAD

**Issue by Antoine-Derouin** [bubelov/news#41]
As it is the case on the "news" tab it would be nice to be able to make a keyword search in "Bookmarks".

**Comment by bubelov** [comment]
@Antoine-Derouin makes sense. Do you think it should be a scoped search (news only, bookmarks only, feeds only, etc) or a single unified search?

**Comment by Antoine-Derouin** [comment]
@bubelov Since there are only three tabs, it seems simpler to me to do three separate searches.

If I want to quickly find an article that I bookmarked, I don't want it to be drowned in the middle of many articles "just read", that would complicate the search ^^

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/03914227a7c49bc5ab5e1dba8d49d97f2f942b0c
