### ISSUE TITLE
Add support for app translations

### ISSUE THREAD

**Issue by Antoine-Derouin** [bubelov/news#42]
I am willing to help translate the app into French. 🇫🇷

**Comment by bubelov** [comment]
@Antoine-Derouin great! Here is your strings file:

https://github.com/bubelov/news/blob/master/app/src/main/res/values-fr/strings.xml

Feel free to replace English values with their French translations. You might want to add this page to your bookmarks and check it from time to time. The app is far from being feature-complete so there will be more strings to translate. 

Here is the example of existing translation (Swedish):

https://github.com/bubelov/news/blob/master/app/src/main/res/values-sv/strings.xml

I think GitHub allows to edit text files right from the browser so there is no need to use Git and clone the whole project.

**Comment by Antoine-Derouin** [comment]
@bubelov Perfect !
