### ISSUE TITLE
Added automatic synchronization at launch

### ISSUE THREAD

**Issue by Antoine-Derouin** [bubelov/news#43]
With an option that can be enabled or disabled in the preference.

**Comment by bubelov** [comment]
@Antoine-Derouin do you think it should be on by default?

**Comment by Antoine-Derouin** [comment]
@bubelov why not, it would help novice people who wouldn't think of "pull for refresh".

**Comment by Antoine-Derouin** [comment]
Also, a "refresh in background" option exists on a lot of apps, it could please some people.

But it's only interesting for receive notifications.

(in my personal case it doesn't interest me)

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/9c0ad271e756cdd3bee8140eef601098a1e29746
