### ISSUE TITLE
About Content

### ISSUE THREAD

**Issue by bakinazik** [bubelov/news#46]
how can i see all content on the page? example flym. when i scroll down on the flym it shows me all the page content.

**Comment by bubelov** [comment]
@bakinazik I'm not sure what do you mean. Some feeds do not provide full content of their posts so you have to go to their websites to see everything. In current News release, you can open the post in the app and then click on the "go to website" action button located in the lower-right corner of the screen. In the next release, there will be an option for every feed that allows users to go straight to websites.

**Comment by bakinazik** [comment]
Can the application completely pull the text in the site under normal conditions? are you sure about this? because I can see the text completely with flym but it is totally not visible in this application.

**Comment by bakinazik** [comment]
![resim](https://user-images.githubusercontent.com/61169988/111977583-f40c0500-8b13-11eb-9d32-31d8b21609a7.png)
![resim](https://user-images.githubusercontent.com/61169988/111977606-fbcba980-8b13-11eb-9b1c-70a01769d16d.png)

**Comment by bubelov** [comment]
@bakinazik if you have a feed URL, it's easy to check if it's full or stripped. Flym might simply try to load HTML and ignore feed content completely, some readers do exactly that.

**Comment by zynexiz** [comment]
NextCloud have the option in the news application, it's not something that's done in the app itself. The implemented "readability" a while ago. I just noticed it myself couple of months ago :)

**Comment by bubelov** [comment]
@zynexiz can you please expand on that? I don't see any related options in the web app

**Comment by zynexiz** [comment]
In the news application in NextCloud you have the option to activate full text for each flow.
![Screenshot_20210404_201114](https://user-images.githubusercontent.com/22789493/113517740-2b51cb80-9582-11eb-8820-0f42d81dd4c6.png)

**Comment by bubelov** [comment]
@zynexiz that's a nice feature, I thought about implementing something like this client-side. What about quality? It must be pretty hard to separate the relevant text from interface elements, ads, weird markup and so on

**Comment by zynexiz** [comment]
It's quite useful so you don't have to leave the app itself, and just get the text (and images) of the article to read. The work is pretty decent I think, not completely flawless though. Some pages will display stuff that's not relevant, but is most cases it works pretty good.

**Comment by bubelov** [comment]
Closing since there are two existing ways to deal with it reliably (opening in browser or changing server-side feed settings)
