### ISSUE TITLE
Mark as read on induvidual feed

### ISSUE THREAD

**Issue by zynexiz** [bubelov/news#47]
While the mark as read was implemented on the main feed, it's not the case while reading the individual feeds. The function should be implemented there for ease of use. Many times I just read some of the individual feeds, but still need to scroll down in the main feed to get them marked as read.

**Comment by bubelov** [comment]
@zynexiz do you mean items don't get marked as read automatically or you just suggesting to add a "mark all as read" button to save users time scrolling trough feeds when they aren't really interested and simply want to mark everything unread as read?

**Comment by zynexiz** [comment]
Items don't get marked as read when scrolling inside individual feeds (from feed tab), like they do in the main feed (where all news are shown). But a "Mark all as read" button would be nice to :)

**Comment by bubelov** [comment]
Fixed in https://github.com/bubelov/news/commit/16d338dbc565f83592072246503ffc61a6ef5fc0
