### ISSUE TITLE
Minor bug in mark as read while scrolling

### ISSUE THREAD

**Issue by zynexiz** [bubelov/news#48]
The mark as read works very good in most cases. Although I noticed an odd behaviour when scrolling down a bit, reading one articles and go back. All the articles visible (unread ones) on the screen when I read one post gets marked as read when going back to the main screen. It seems like the app reloads the feed in all, so the last article not shown in the view will be the first one on top. This don't happen if you read the articles at the top, and not started scrolling down in the list.

Think a good way to mitigate this is to keep the main feed "intact" when going back, until a refresh of the feeds is issued (think the official NextCloud News app handles it this way).

**Comment by bubelov** [comment]
@zynexiz yes, return to the feed shouldn't cause all of its items to reload. I think I already fixed this in the unreleased code. Feel free to re-open this issue if it persists after the next update.

PS. There is one edge case where this issue will always be present: if you open your news entry in a browser or decide to switch to some resource-heavy game and come back the app later, its state can be destroyed by the OS on order to allocate some RAM for other tasks and it will indeed cause all data to reload. Most of the times this shouldn't happen, though.

**Comment by zynexiz** [comment]
@bubelov Ah, sounds good :) I will check the next release when it gets out and see if it's fixed there.

Yeh, most applications have this behaviour. Mostly depends how much other stuff is running :)
