### ISSUE TITLE
Italian translation 🇮🇹 

### ISSUE THREAD

**Issue by seldon1000** [bubelov/news#50]
I noticed that you're not using any localization platform, so I'm opening this issue. I'm willing to translate the app in Italian 🇮🇹 .

**Comment by bubelov** [comment]
@seldon1000 I never used localization platforms. Frankly, I don't see any value in it. I might be wrong, but most of the people who use RSS or Atom feeds are tech workers and they understand English. I don't even have a translation for my own native language. That was an initial assumption but then people started to show up and suggest translations, so, at this point, using a platform starts to look like a good idea. Do you have any recommendations?

I've added an Italian translation file here: https://github.com/bubelov/news/blob/master/app/src/main/res/values-it/strings.xml

The file above contains in-app strings only, store descriptions and other localizable resources can be found here: https://github.com/bubelov/news/tree/master/fastlane/metadata/android/it

**Comment by seldon1000** [comment]
@bubelov Yeah, I'm perfectly fine with English too, but having at least an UI in your own language can be comforting. I think that even more people will show up once they see you're using an actual platform, since it's more approachable.

> Do you have any recommendations?

Well, I'm a translator for other four projects and they're using Crowdin and Weblate (hosted). They're both pretty good for a translator, but I can't tell for a developer. However, a couple of months ago, I was translating an app on Transifex (poor experience, I'd avoid it) and soon after the dev switched to Crowdin claiming that it was much better. You could check those out and decide by yourself. If you ask me, I tend to prefer Crowdin.

> I've added an Italian translation file here: https://github.com/bubelov/news/blob/master/app/src/main/res/values-it/strings.xml
> 
> The file above contains in-app strings only, store descriptions and other localizable resources can be found here: https://github.com/bubelov/news/tree/master/fastlane/metadata/android/it

Great! I'll work on it asap.

**Comment by bubelov** [comment]
@seldon1000 thanks for your contribution! One more question about platforms: what do you think about providing direct edit links to strings.xml file for each language? It doesn't require people to deal with forks, commits and pull requests, it's as simple as editing a text file in a browser. Here is the example of such a link:

https://github.com/bubelov/news/edit/master/app/src/main/res/values-it/strings.xml

I could put links for every language on the main page, in the "contribute" section or something like that. Is it significantly less user friendly than translation platforms?

**Comment by seldon1000** [comment]
@bubelov  Honestly, it would be much less friendly. On Crowdin, for instance, we (translators) are automatically notified when new untranslated strings are available; we can write comments asking for clarifications (when we're not sure what the strings actually mean); we can suggest new translations and so on. People will request a new language and, if approved, proceed translating without any hassle whenever they want. You will have to import new translations from time to time.

At the moment, there's basically just one file to translate and there is just a bunch of strings, so using a simple direct link, as you suggest, could be a temporary solution. However, expecting this project to grow, doing so will become just too problematic at some point.
