### ISSUE TITLE
Add "mark all as read"

### ISSUE THREAD

**Issue by Antoine-Derouin** [bubelov/news#53]
It happens that on the server side, a feed displays all the articles of a site as unread.

It would be convenient in Feeds, added to the three dots menu, "mark all as read".

It could also be useful to have this button in the "News" tab for all feeds at once.

In any case, make sure to put a popin to confirm the action !

**Comment by bubelov** [comment]
@Antoine-Derouin it's already implemented and it will be available in the next version. Probably in a week or so =)
