### ISSUE TITLE
Transtaling the app

### ISSUE THREAD

**Issue by bubelov** [bubelov/news#54]
I've integrated translation platform Crowdin, it should make it simpler to contribute new translations. Direct pull-requests are still welcome, in case you don't want to use this platform. Here is the link:

https://crwd.in/news-android

Feel free to test it and leave your feedback.

CC @zynexiz @Antoine-Derouin @seldon1000 @agustinca635

**Comment by seldon1000** [comment]
That's awesome! I've already translated some strings and it works great. I'll definitely keep the italian translations updated. Thank you.
