### ISSUE TITLE
[Feature Request] Limit the number of articles listed in News section

### ISSUE THREAD

**Issue by seldon1000** [bubelov/news#56]
Right now, if I don't hide read articles, the News section quickly becomes cluttered with hundreds of articles from previous days. The user should be able to limit the number of articles and I can suggest two ways to do that:

- limit the actual number, like "list max 50 articles";
- choose for how long an article should be listed, like "keep articles for two days" and then remove them.

**Comment by bubelov** [comment]
@seldon1000 users can hide read news and it's the default filter. I don't really see a point in hiding content from a user when he specifically requested to see all of the news. I rarely use a "full view", only when I want to find something that I read a few days ago. Hiding some news would make this task difficult and unpredictable.

Can you expand on your use case with read news?

**Comment by seldon1000** [comment]
@bubelov sure, I'll be more specific. I should clarify that I don't read every news, just a few, and that the use case I was referring to implies that news are marked as read on scroll.

We can imagine three types of news: non-read, read and discarded (news I've seen while scrolling but I don't want to read). Basically, I open the app to see if there are any non-read news, so I start scrolling, but when should I stop? I'm used to stop when I see a read news (I recognize it because it's dimmed, that's why I don't like hiding them), but what happens if I haven't read any news for quite some time, while still using the app to just scroll them? I could start scrolling through old discarded news without realizing it (unless I remember their titles). Limiting the news by their age (like, keep news for two days) would help preventing this from happening, because at some point I would reach the end of the list.

I thought I could just mark news as read on scroll, but this way there is no distinction between read and non-read.

**Comment by bubelov** [comment]
@seldon1000 why don't you hide read news by default? In this mode, the app would never show you the news you already clicked on or swiped on. If you also enable "mark scrolled as read", there would be no need to interact with news in any way. The app would only show you unread news after you open it, isn't it your goal?

**Comment by seldon1000** [comment]
@bubelov hmm, I should try as you say. I guess I'm still used to Flym and to how it managed news. However, I have one last question before closing this issue. How are old news managed? I mean, does the app keep everything in cache or does it retrieve news dynamically while scrolling?

**Comment by bubelov** [comment]
@seldon1000 the app does not depend on Internet connection. It keeps everything in cache, even images. Search is also completely local, so it should work even when user in on a plane. If your NC instance has something, your Android app has it too.

It's not always a good thing, though. I have more than 30k news items and the initial sync takes a while. One of my low-prio plans is to sync only unread news after the login and sync the rest of the history in background, without blocking the user.

Another side effect is storage bloat. The app has no storage management capabilities at the moment. At some point, it should be solved by limiting the size of read news database. It can be done by news count, by date or by the actual DB size (in (M|G)bytes), I haven't decided yet.

**Comment by seldon1000** [comment]
@bubelov as I thought, it was just too fast to load on demand. I think this improves the experience overall but, as you said, there are some side effects.

So your plan is to limit the read news number, but unread news would stay unlimited, right? If so, I am worried about the storage usage on my device too; it's not a problem at the moment, but some months from now? As I said before, I don't read everything, and keeping very old news I don't want to read in storage could lead to some problems. I might be able to settle with "mark read on scroll" and let the app do its magic, but other users could have my same issue.

The app could only load most recent news by default and then load older news on demand (by scrolling or clicking some button like "Load more..."). There would be no need for a user setting, just do it automatically.

**Comment by bubelov** [comment]
@seldon1000 it would complicate the code and it would also mess with Nextcloud settings. Your instance already has certain data policies, you can inspect and edit them according to your preferences. I don't think client apps should mess with that. I wouldn't appreciate inconsistent results between different clients.

News don't take much space anyway. The main offender is podcasts, and I guess we have to deal with them first.

**Comment by bubelov** [comment]
@seldon1000 my example with 30k news is rather extreme, it happens only because I explicitly blocked the server from removing any data from its database. The app does exactly what user should expect with such settings. The default server behavior is to keep no more than 1,000 items in each feed, if I remember correctly. You can go to your instance and set this number to whatever suits you best.

**Comment by seldon1000** [comment]
@bubelov I didn't know I could do that, sounds cool. I only recently switched to a Nextcloud based storage service (before going full selfhosted) and I'm still learning how to use it properly. Thanks for the tip.

Closing.
