### ISSUE TITLE
[Feature Request] Click "News" button to go back on top

### ISSUE THREAD

**Issue by seldon1000** [bubelov/news#57]
I find myself scrolling down through the News section and then having to scroll back up compulsively just to reach the top again. Maybe, add the possibility to click (or double click) on News button to go back on top.

**Comment by bubelov** [comment]
Added in https://github.com/bubelov/news/commit/88c6a1a4224287a61e99e60dd811d396b97e79c0

**Comment by bubelov** [comment]
@seldon1000 you'll have to tap on the bottom bar icon to "reset" the list state (go back to position 0). I borrowed this pattern from Gmail

**Comment by seldon1000** [comment]
Awesome, thank you!
