### ISSUE TITLE
Multiple feeds with different xmlUrl but same htmlUrl cannot be added

### ISSUE THREAD

**Issue by Tiger3030** [bubelov/news#58]
There are some RSS feed providers that do not set the exact url but the homepage of their website as htmlUrl. So they have different RSS feeds with different content, but the same htmlUrl, for example:

Feed 1: xmlUrl = 'https://example.com/feed1', htmlUrl = 'https://example.com'
Feed 2: xmlUrl = 'https://example.com/feed2', htmlUrl = 'https://example.com'

When you add the second feed to the app the first feed is deleted again, so you can only add one feed from websites where this is the case.

**Comment by bubelov** [comment]
@Tiger3030 are you using Nextcloud or Standalone mode?

**Comment by Tiger3030** [comment]
I am using Standalone mode

**Comment by bubelov** [comment]
@Tiger3030 Standalone mode used HTML URLs as IDs. I changed it to XML (feed) URLs, it should help the app to avoid conflicts

Fixed in https://github.com/bubelov/news/commit/0d7fe1587d3578a3cb7bcd0b4ed1b4c6d0427be0

**Comment by TheOne-Z** [comment]
I'm having this issue with few of my feeds, running in standalone mode.
Examples: 
https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NEWS&concepts=18-218706
and
https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NEWS&concepts=18-214247
