### ISSUE TITLE
Add feed URL handlers

### ISSUE THREAD

**Issue by Farzat07** [bubelov/news#66]
When opening rss urls, show this app as an option to allow quick subscribing to feeds.
![Screenshot_20210513_223033](https://user-images.githubusercontent.com/55144155/118132721-f9fad400-b43a-11eb-9f03-886206633f2f.jpg)

**Comment by bubelov** [comment]
@Farzat07 what's the name of this app? Is it open source?

**Comment by Farzat07** [comment]
Yes. It is called Feeder (https://gitlab.com/spacecowboy/Feeder).

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/c4760a0d021906babca632335eb02260f38eb24e
