### ISSUE TITLE
Some feed items showing as "Unknown feed" (Standalone Mode)

### ISSUE THREAD

**Issue by MarissaRS** [bubelov/news#70]
Device: Google Pixel 4, Android 11 (Calyx OS)

After the latest update from F-Droid, many of my feed items are displaying as "Unknown feed" and don't open anything when I tap them. 

Example:

![Screenshot-2021-05-27-12-01-12.png.jpg](https://user-images.githubusercontent.com/54009117/119859430-61a52a80-bee3-11eb-9289-b335ae7181ed.jpg)

As you can see in the screenshot, one feed item is fine and the other shows as "Unknown feed"

**Comment by bubelov** [comment]
@MarissaRS fixed in https://github.com/bubelov/news/commit/211589d9f00cf28e3a8bf37ea048dad15e0b09a5, will be rolled out with the next release
