### ISSUE TITLE
Non-breaking spaces are dropped from text

### ISSUE THREAD

**Issue by mormegil-cz** [bubelov/news#71]
There is explicit code to remove all U+00A0 characters from the entry text in `entry.EntryViewModel#parseEntryContent`. I have no idea why it was introduced or for which problem should this be a solution. However, this is (quite obviously, I’d say) wrong. U+00A0 is a space character. By removing some subset of space characters from text, the text obviously… misses some spaces, having words joined which should not have been.

For a completely random example, see e.g. https://k47.cz/rss.xml and [its (currently) first item](https://k47.cz/2021/sex.html), beginning with //Z ur­či­tých// with a nbsp character there in the middle. The app currently drops the space character, rendering this as //Zurčitých//.

Note that the short preview in the overview screen does not have the problem, showing spaces correctly.

**Comment by bubelov** [comment]
@mormegil-cz its hard to say now why it was here, but my current feeds seem to work fine without this code. I removed it, hopefully it won't break anything else and people won't go here to complain =)

Fixed in https://github.com/bubelov/news/commit/8823bf16b2e59b97e98f3f5c18d0d034d3643ddd
