### ISSUE TITLE
Synchronization faulty

### ISSUE THREAD

**Issue by dermitdemdino** [bubelov/news#78]
The synchronization between app and server is not synchronous.

**Comment by bubelov** [comment]
Can you provide more details on that? Do you get new items from server?

**Comment by dermitdemdino** [comment]
The feeds are synchronized and retrieved - but incorrectly. Attached is an example:

Dektop:

Unread: 113
Linux: 0
Nitter: 2
Politics: 4
RSS: 107

Android:

Unread: 6080
Linux: 38
Nitter: 1046
Politics: 613
RSS: 4383

![android](https://user-images.githubusercontent.com/6813869/135704977-74442beb-1a1d-40ca-b9a5-f396145c5b99.png)
![desktop](https://user-images.githubusercontent.com/6813869/135704980-88f3b3c4-5bf0-44e8-a7e8-876e8096fea6.png)

**Comment by bubelov** [comment]
@dermitdemdino it doesn't look like the app from this repo. It looks similar to this app, perhaps you can move your issue there:

https://github.com/nextcloud/news-android

**Comment by dermitdemdino** [comment]
Thanks for pointing that out, and sorry for the confusion. I have now installed this app, and it works - and syncs perfectly (still). Thanks again!
