### ISSUE TITLE
Picture only feed not displayed correctly

### ISSUE THREAD

**Issue by nabakolu** [bubelov/news#79]
When a feed only contains an image, the image is cropped somehow.

### Here is how it is displayed:
![Screenshot_20210914-163020_News](https://user-images.githubusercontent.com/55393142/134820088-85039012-a18b-4e5e-9e2d-71a05fc0564c.png)

### Here is how the app Flym displays it:
![Screenshot_20210914-162949_Flym_DecSync](https://user-images.githubusercontent.com/55393142/134820098-43ec6d9d-c872-4374-bfbb-e2f4be80f066.png)

### Here is the actual image in the feed:
![vaccine_research](https://user-images.githubusercontent.com/55393142/134820106-c5a38f77-af5f-4f13-8d08-c223440b2502.png)

**Comment by bubelov** [comment]
@nabakolu thanks for reporting, I'll have a look. Meanwhile, you can disable image cropping in settings in order to see full images right from the feed itself:

![Screenshot_20210927-193426_News Debug](https://user-images.githubusercontent.com/1189245/134909263-23c427a9-33c7-45d2-b53f-717fa2fe87a1.jpg)

**Comment by bubelov** [comment]
@nabakolu I couldn't reproduce it in the current master branch, does this cropping affect all xkcd posts or only the one from your example?

![Screenshot_20210927-210955_News Debug](https://user-images.githubusercontent.com/1189245/134925796-7287eea3-d43b-414b-9629-5c03c62dbcf4.jpg)

**Comment by nabakolu** [comment]
It affects every xkcd post

**Comment by bubelov** [comment]
@nabakolu I see, it's probably already fixed. Leaving this issue open, will check again before release to make sure it works in all three backends (Nextcloud, Miniflux, Standalone)

**Comment by nabakolu** [comment]
Yea I just tried on the latest build and it works perfectly
