### ISSUE TITLE
Open in browser

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#82]
Make it possible to open articles directly in the browser.

In this example you see a problem with the current implementation:

https://user-images.githubusercontent.com/50382414/135778695-29a212b4-31e4-450f-aba6-4c0070051388.mp4

Feeds:
- http://www.nos.nl/nos/rss/nieuws.xml
- https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw
- https://www.reddit.com/r/fossdroid/.rss

The first feed is an official rss feed, second is youtube and third reddit. The 2nd and 3rd feeds cannot be opened. If open in browser is enabled, android will automatically open reddit feeds in the reddit app and youtube feeds in the youtube app (without ever opening a browser). I also suggest making the option "open in browser" a per feed setting.

**Comment by bubelov** [comment]
@Donkey-Doug try grabbing the latest APK from GitHub actions, I think those features are already implemented. It should also fix your issue with "unknown" feeds

**Comment by bubelov** [comment]
@Donkey-Doug by the way, make sure you have your OPML backed up, next release will have a lot of breaking changes for standalone mode

**Comment by Donkey-Doug** [comment]
> @Donkey-Doug try grabbing the latest APK from GitHub actions, I think those features are already implemented. It should also fix your issue with "unknown" feeds

I was using version 0.2.9 (latest) from fdroid.

**Comment by bubelov** [comment]
@Donkey-Doug F-Droid only contains released builds, this issue is fixed in unreleased dev build. You can either wait for the next release or install the latest version from GitHub CI

**Comment by Donkey-Doug** [comment]
> @Donkey-Doug F-Droid only contains released builds, this issue is fixed in unreleased dev build. You can either wait for the next release or install the latest version from GitHub CI

Would love to test, but couldnot find the apk. Most github pages  have pre-release version in the release section. If you show me in the right direction, I can test the app for you.

**Comment by bubelov** [comment]
@Donkey-Doug yea, this process is not finalized yet, it will probably have a changing "nightly" release and a build script which updates it after every commit

For now, you can go there: https://github.com/bubelov/news/actions

Every new commit triggers unit tests and produces an APK file which can be installed. You can click on the latest job and download the attachment, it's called news-debug and it's an archive with a usual APK. It will not conflict with the app from F-Droid, you can have both versions installed simultaneously

**Comment by Donkey-Doug** [comment]
The unknown feed and open in browser issues are fixed
