### ISSUE TITLE
Force Close with Version 0.3.0

### ISSUE THREAD

**Issue by c64bob** [bubelov/news#94]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Start the app, optionally clear cache before
2. it immediately force closes

### Actual behavior

After update from version 0.2.9 to 0.3.0 the app doesn't start anymore, but force closes immediately.

### Device info

 - Android version/Custom ROM version: Android 12
 - Device model: Pixel 5

**Comment by bubelov** [comment]
@c64bob did you try to delete the app manually and make a clean install?

**Comment by c64bob** [comment]
Yes, I tried that as well. Unfortunately it still force closes after a clean install.

**Comment by bubelov** [comment]
@c64bob ah, I see. Its Android 12... See https://github.com/bubelov/news/pull/88

I'll patch this thing soon. Meanwhile, you can use preview build:

https://github.com/bubelov/news/releases/tag/preview

**Comment by bubelov** [comment]
@c64bob also, https://github.com/bubelov/news/issues/92. Android 12 will have a new customizable theme, I'm working on it now and I'll make a new release in a day or two, but it can take F-Droid a few days to distribute it

**Comment by bubelov** [comment]
Fixed in v0.3.1
