### ISSUE TITLE
Unable to add rss feed manually

### ISSUE THREAD

**Issue by defenset** [bubelov/news#96]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Try to add feed.

### Actual behavior

For some reason I’m not able to add custom feed.

### Expected behavior

Be able to add custom feed

### Screenshots/Screen recordings

![feed adding error](https://user-images.githubusercontent.com/94124619/142228561-21ca3e8e-3c44-4db3-a1d0-7f6e802a3d2c.png)

**Comment by bubelov** [comment]
@defenset I was able to reproduce this issue. For some reason, HN refuses to send its feed to the app. Here is the full error:

![Screenshot_1637230678](https://user-images.githubusercontent.com/1189245/142396879-5cd77c33-e66a-49f2-b703-7121bb8635fc.png)

HTTP response code: 503
Message: Sorry, we're not able to serve your requests this quickly

It looks like an issue on HN side, maybe it bans requests based on user agent headers or something. I'll look into this later, but there are no clean solutions AFAIK

The error message should be more informative though, I'll add more details for this kind of errors

**Comment by bubelov** [comment]
The app sent two requests instead of one, one by the app itself and one by a feed parser library. That might explain rate limiting on certain websites. I'll configure the lib not to send a second request, maybe it will solve this issue

**Comment by bubelov** [comment]
Ok, it seems to be working now. It's available in preview release now and it will be available in F-Droid in a few days. Let's leave the issue open till the fix is available in F-Droid

**Comment by defenset** [comment]
ok, I will test it as soos as it's out

**Comment by defenset** [comment]
Works perfectly, you can close this issue, 🥇

**Comment by defenset** [comment]
Here is [another one](https://distrowatch.com/news/dwd.xml
) that I tried but couldn't load on **news**, if you can @bubelov, take a look at it
