### ISSUE TITLE
Unable to import feeds from opml file

### ISSUE THREAD

**Issue by defenset** [bubelov/news#97]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Try to import opml file

### Actual behavior

ompl file is invalid

### Expected behavior

Be able to import

### Screenshots/Screen recordings

[test.feed.txt](https://github.com/bubelov/news/files/7555819/test.feed.txt)

**Comment by defenset** [comment]
![feed import error](https://user-images.githubusercontent.com/94124619/142230142-902ce344-7699-477d-9c67-70d59ec19226.png)

**Comment by bubelov** [comment]
@defenset this OPML file is invalid, see https://github.com/bubelov/news/issues/81#issuecomment-934504050

All OPML files are required to have an attribute named "text". You can try filing a bug report for the app which created this invalid feed

**Comment by defenset** [comment]
it was flym, but it's abandoned now, unfortunately

**Comment by bubelov** [comment]
@defenset you can open your OPML as a text file and rename all `title` attributes to `text`. One "find and replace" operation should make your OPML valid and compatible with all readers

**Comment by defenset** [comment]
I'll do that, hopefully your app will replace it for me in some future 🤞
